name: Regression suite
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 2 * * *'  # Fixed cron syntax (runs at 02:30 UTC daily)

jobs:
  run-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: true  # Optional: Continue even if dependencies fail to install

      - name: Run tests
        run: |
          pytest -s --html=report.html --self-contained-html  # Fixed pytest HTML report syntax

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: pytest-report
          path: report.html
